[package]
name = "aio-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
aio-ipc = { version = "0.1.0", path = "../aio-ipc" }
anyhow = "1.0.104"
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow"] }
egui = "0.36.2"
image = { version = "0.25.10", default-features = false, features = ["jpeg"] }
rfd = "0.17.2"
tray-icon = "0.26.0"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }
